CREATE TABLE IF NOT EXISTS ROLEDAO (
ID INTEGER AUTO_INCREMENT,
name VARCHAR(255) NOT NULL UNIQUE);

CREATE TABLE IF NOT EXISTS USERDAO (
ID INTEGER AUTO_INCREMENT,
login VARCHAR(100) UNIQUE,
password VARCHAR(100),
email VARCHAR(100) UNIQUE,
firstname VARCHAR(100),
lastname VARCHAR(100),
birthday DATE,
id_Role LONG NOT NULL);