  CREATE TABLE IF NOT EXISTS ROLEDAO
    (
    id IDENTITY,
    name VARCHAR(256) NOT NULL UNIQUE
    );

CREATE TABLE IF NOT EXISTS USERDAO
  (
  id IDENTITY,
  login VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  firstName VARCHAR(255) ,
  lastName VARCHAR(255),
  birthday DATE,
  id_Role LONG NOT NULL
    );
